### ISSUE TITLE
Wallpaper issues

### ISSUE THREAD

**Issue by madsrh** [Feichtmeier/settings#116] opened 2021-10-02 21:15 UTC
I know everything is WIP but I'm submitting this anyway. If you're already aware of these issues, just ignore this :smile: 

1. Wording: When selecting a directory, the button on the orange bar at the bottom, should be labeled "Select directory" and not "Select **a** directory". 

2. In the "dialogs" for _Select a wallpaper_ and _Select a location_, the breadcrumb labels needs styling (they aren't visible) 

3. If you click _Select a wallpaper_ and then close the dialog, the current wallpaper is removed.

4. The wording _Select a wallpaper_ is a bit odd IMHO because the user is already selecting a wallpaper in the grid below. Perhaps it would be more fitting with something like: Add picture, browse photos, ...
Similarly the location button doesn't actually change the location, but adds a folder, so perhaps add location or add folder would be more fitting.

5. There's something odd in the dialog when selection a file: You can't click the filename and only jpg files are available (not png, gif,...)

6. Also just noticed that when adding a location, the added folder isn't saved when you revisit the wallpaper settings page.

![Peek 2021-10-02 22-58](https://user-images.githubusercontent.com/3986894/135731246-77b2453c-71c6-4ea0-b765-ea3da0ad6c3e.gif)

**Comment by Feichtmeier** [comment] 2021-10-02 21:40
The issue with the appbar should be fixed inside the file picker package we use "upstream"

The other issue is def a bug introduced by me, thanks!

**Comment by Jupi007** [comment] 2021-10-02 21:43
@Feichtmeier It is possible to customize folder icons inside the file picker?

**Comment by Feichtmeier** [comment] 2021-10-02 21:44
Only the color ... which turned to be pink in the light theme xD 
Eventually we should fork the file picker because it looks kind inactive? Or try to improve it. But I think it is also possible to create our own filepicker with this package

**Comment by Jupi007** [comment] 2021-10-02 21:46
Nice, those folder icons make me sad 😅

**Comment by madsrh** [comment] 2021-10-02 22:02
Maybe a monochrome style would work great here, like just use the symbolic icons :man_shrugging: 

Also just noticed that when adding a location, the added folder isn't saved.

**Comment by Feichtmeier** [comment] 2021-10-02 22:48
> 
> 
> Maybe a monochrome style would work great here, like just use the symbolic icons 🤷‍♂️
> 
> Also just noticed that when adding a location, the added folder isn't saved.

monochrome is actually the default so we could just remove the color property 
the problem with the not persistant location is that we need to store it outside of the app, so this is basically a missing feature not a bug but on the todo

**Comment by Feichtmeier** [comment] 2021-10-04 13:38
https://github.com/andyduke/filesystem_picker/pull/32

**Closed** 2021-10-04 14:03 UTC
Labels: bug, enhancement
